Added scripts for creating the species section of an ARC input file
DanaResearchGroup/DRGScripts pull request #16
Opened 2023-06-25 11:49 UTC by alongd

2023-06-27 08:58 UTC, NellyMitnik commented
While loading the chemkin file, a flag of ```check_duplicates=False``` , should be added. 
Otherwise, there will be errors such as: 
```
~/Code/RMG-Py/rmgpy/chemkin.pyx in rmgpy.chemkin.load_chemkin_file()

~/Code/RMG-Py/rmgpy/chemkin.pyx in rmgpy.chemkin._process_duplicate_reactions()

ChemkinError: Encountered unmarked duplicate reaction OH(7) + HCCO(79) <=> CO(47) + HCOH(60).
```

2023-06-27 09:01 UTC, NellyMitnik requested changes
The flag: ```check_duplicates=False``` ,should be added while loading a chemkin file.

2023-07-01 10:02 UTC, alongd commented
Thanks! fixed

2023-07-01 12:36 UTC, NellyMitnik approved these changes

2023-07-01 12:36 UTC, merged